name: Build & Run
run-name: ${{ github.actor }}'s build
on:
  push:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Install Modules
        run: npm install --save-dev
      - name: Build
        run: npm run build
      
